spring:
  profiles.active: test

---

spring:
  profiles: test
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/db_user?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true
    url: jdbc:mysql://127.0.0.1:3306/db_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Bjh123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 100
    min-idle: 2
    validation-query: SELECT 1
  rabbitmq:
    username: bao
    password: bao
    host: 39.106.28.99
    port: 5672
    listener:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 2
        multiplier: 1.5
        max-interval: 5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: Bjh123456
    database: 0
    pool:
      max-active: 200
      max-wait: 10000
      max-idle: 100
      min-idle: 5

mybatis:
  config-location: classpath:mybatis-config.xml

# 查询180的
#elasticsearch:
#  cluster-name: my-application
#  cluster-nodes: 172.18.6.180:9300
#  order.index: test_account_action
#  order.type: t_account_action

# 查询99的
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 127.0.0.1:9300
  order.index: mapping_account_action
  order.type: t_account_action

#elasticsearch:
#  cluster-name: elasticsearch
#  cluster-nodes: 127.0.0.1:9300
#  order.index: test_user
#  order.type: tbl_user
